add support for --root-issuer when generating CCI claims (#438)
* add support for --root-issuer when generating CircleCI OIDC token

make this default behaviour

https://github.com/di/id/issues/437
Signed-off-by: meeech <4623+meeech@users.noreply.github.com>

* use stderr instead of stdout to surface error generating roken with circleci binary

This then produces an error message of

```
 CircleCI: the `circleci` tool encountered an error: oidc: error: failed to get oidc token: this project does not allow issuing tokens to forks
Error: exit status 1: oidc: error: failed to get oidc token: this project does not allow issuing tokens to forks
```

Signed-off-by: meeech <4623+meeech@users.noreply.github.com>

---------

Signed-off-by: meeech <4623+meeech@users.noreply.github.com>